name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          wget -q http://mirrors.kernel.org/ubuntu/pool/main/libb/libbpf/libbpf0_0.4.0-1ubuntu1_amd64.deb
          wget -q http://mirrors.kernel.org/ubuntu/pool/main/libb/libbpf/libbpf-dev_0.4.0-1ubuntu1_amd64.deb
          sudo apt-get install -y libelf-dev libc6-dev-i386
          sudo dpkg -i libbpf0_0.4.0-1ubuntu1_amd64.deb libbpf-dev_0.4.0-1ubuntu1_amd64.deb
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: make
